import { DatabaseSync } from "node:sqlite";

const db = new DatabaseSync("pokescan.sqlite");

type PokemonSeed = {
  number: number;
  name: string;
  type1: string;
  type2?: string;
};

const pokemon: PokemonSeed[] = [
  { number: 1, name: "Bulbasaur", type1: "Grass", type2: "Poison" },
  { number: 2, name: "Ivysaur", type1: "Grass", type2: "Poison" },
  { number: 3, name: "Venusaur", type1: "Grass", type2: "Poison" },
  { number: 4, name: "Charmander", type1: "Fire" },
  { number: 5, name: "Charmeleon", type1: "Fire" },
  { number: 6, name: "Charizard", type1: "Fire", type2: "Flying" },
  { number: 7, name: "Squirtle", type1: "Water" },
  { number: 8, name: "Wartortle", type1: "Water" },
  { number: 9, name: "Blastoise", type1: "Water" },
  { number: 10, name: "Caterpie", type1: "Bug" },
  { number: 11, name: "Metapod", type1: "Bug" },
  { number: 12, name: "Butterfree", type1: "Bug", type2: "Flying" },
  { number: 13, name: "Weedle", type1: "Bug", type2: "Poison" },
  { number: 14, name: "Kakuna", type1: "Bug", type2: "Poison" },
  { number: 15, name: "Beedrill", type1: "Bug", type2: "Poison" },
  { number: 16, name: "Pidgey", type1: "Normal", type2: "Flying" },
  { number: 17, name: "Pidgeotto", type1: "Normal", type2: "Flying" },
  { number: 18, name: "Pidgeot", type1: "Normal", type2: "Flying" },
  { number: 19, name: "Rattata", type1: "Normal" },
  { number: 20, name: "Raticate", type1: "Normal" },
  { number: 21, name: "Spearow", type1: "Normal", type2: "Flying" },
  { number: 22, name: "Fearow", type1: "Normal", type2: "Flying" },
  { number: 23, name: "Ekans", type1: "Poison" },
  { number: 24, name: "Arbok", type1: "Poison" },
  { number: 25, name: "Pikachu", type1: "Electric" },
  { number: 26, name: "Raichu", type1: "Electric" },
  { number: 27, name: "Sandshrew", type1: "Ground" },
  { number: 28, name: "Sandslash", type1: "Ground" },
  { number: 29, name: "Nidoran♀", type1: "Poison" },
  { number: 30, name: "Nidorina", type1: "Poison" },
  { number: 31, name: "Nidoqueen", type1: "Poison", type2: "Ground" },
  { number: 32, name: "Nidoran♂", type1: "Poison" },
  { number: 33, name: "Nidorino", type1: "Poison" },
  { number: 34, name: "Nidoking", type1: "Poison", type2: "Ground" },
  { number: 35, name: "Clefairy", type1: "Fairy" },
  { number: 36, name: "Clefable", type1: "Fairy" },
  { number: 37, name: "Vulpix", type1: "Fire" },
  { number: 38, name: "Ninetales", type1: "Fire" },
  { number: 39, name: "Jigglypuff", type1: "Normal", type2: "Fairy" },
  { number: 40, name: "Wigglytuff", type1: "Normal", type2: "Fairy" },
  { number: 41, name: "Zubat", type1: "Poison", type2: "Flying" },
  { number: 42, name: "Golbat", type1: "Poison", type2: "Flying" },
  { number: 43, name: "Oddish", type1: "Grass", type2: "Poison" },
  { number: 44, name: "Gloom", type1: "Grass", type2: "Poison" },
  { number: 45, name: "Vileplume", type1: "Grass", type2: "Poison" },
  { number: 46, name: "Paras", type1: "Bug", type2: "Grass" },
  { number: 47, name: "Parasect", type1: "Bug", type2: "Grass" },
  { number: 48, name: "Venonat", type1: "Bug", type2: "Poison" },
  { number: 49, name: "Venomoth", type1: "Bug", type2: "Poison" },
  { number: 50, name: "Diglett", type1: "Ground" },
  { number: 51, name: "Dugtrio", type1: "Ground" },
  { number: 52, name: "Meowth", type1: "Normal" },
  { number: 53, name: "Persian", type1: "Normal" },
  { number: 54, name: "Psyduck", type1: "Water" },
  { number: 55, name: "Golduck", type1: "Water" },
  { number: 56, name: "Mankey", type1: "Fighting" },
  { number: 57, name: "Primeape", type1: "Fighting" },
  { number: 58, name: "Growlithe", type1: "Fire" },
  { number: 59, name: "Arcanine", type1: "Fire" },
  { number: 60, name: "Poliwag", type1: "Water" },
  { number: 61, name: "Poliwhirl", type1: "Water" },
  { number: 62, name: "Poliwrath", type1: "Water", type2: "Fighting" },
  { number: 63, name: "Abra", type1: "Psychic" },
  { number: 64, name: "Kadabra", type1: "Psychic" },
  { number: 65, name: "Alakazam", type1: "Psychic" },
  { number: 66, name: "Machop", type1: "Fighting" },
  { number: 67, name: "Machoke", type1: "Fighting" },
  { number: 68, name: "Machamp", type1: "Fighting" },
  { number: 69, name: "Bellsprout", type1: "Grass", type2: "Poison" },
  { number: 70, name: "Weepinbell", type1: "Grass", type2: "Poison" },
  { number: 71, name: "Victreebel", type1: "Grass", type2: "Poison" },
  { number: 72, name: "Tentacool", type1: "Water", type2: "Poison" },
  { number: 73, name: "Tentacruel", type1: "Water", type2: "Poison" },
  { number: 74, name: "Geodude", type1: "Rock", type2: "Ground" },
  { number: 75, name: "Graveler", type1: "Rock", type2: "Ground" },
  { number: 76, name: "Golem", type1: "Rock", type2: "Ground" },
  { number: 77, name: "Ponyta", type1: "Fire" },
  { number: 78, name: "Rapidash", type1: "Fire" },
  { number: 79, name: "Slowpoke", type1: "Water", type2: "Psychic" },
  { number: 80, name: "Slowbro", type1: "Water", type2: "Psychic" },
  { number: 81, name: "Magnemite", type1: "Electric", type2: "Steel" },
  { number: 82, name: "Magneton", type1: "Electric", type2: "Steel" },
  { number: 83, name: "Farfetch'd", type1: "Normal", type2: "Flying" },
  { number: 84, name: "Doduo", type1: "Normal", type2: "Flying" },
  { number: 85, name: "Dodrio", type1: "Normal", type2: "Flying" },
  { number: 86, name: "Seel", type1: "Water" },
  { number: 87, name: "Dewgong", type1: "Water", type2: "Ice" },
  { number: 88, name: "Grimer", type1: "Poison" },
  { number: 89, name: "Muk", type1: "Poison" },
  { number: 90, name: "Shellder", type1: "Water" },
  { number: 91, name: "Cloyster", type1: "Water", type2: "Ice" },
  { number: 92, name: "Gastly", type1: "Ghost", type2: "Poison" },
  { number: 93, name: "Haunter", type1: "Ghost", type2: "Poison" },
  { number: 94, name: "Gengar", type1: "Ghost", type2: "Poison" },
  { number: 95, name: "Onix", type1: "Rock", type2: "Ground" },
  { number: 96, name: "Drowzee", type1: "Psychic" },
  { number: 97, name: "Hypno", type1: "Psychic" },
  { number: 98, name: "Krabby", type1: "Water" },
  { number: 99, name: "Kingler", type1: "Water" },
  { number: 100, name: "Voltorb", type1: "Electric" },
  { number: 101, name: "Electrode", type1: "Electric" },
  { number: 102, name: "Exeggcute", type1: "Grass", type2: "Psychic" },
  { number: 103, name: "Exeggutor", type1: "Grass", type2: "Psychic" },
  { number: 104, name: "Cubone", type1: "Ground" },
  { number: 105, name: "Marowak", type1: "Ground" },
  { number: 106, name: "Hitmonlee", type1: "Fighting" },
  { number: 107, name: "Hitmonchan", type1: "Fighting" },
  { number: 108, name: "Lickitung", type1: "Normal" },
  { number: 109, name: "Koffing", type1: "Poison" },
  { number: 110, name: "Weezing", type1: "Poison" },
  { number: 111, name: "Rhyhorn", type1: "Ground", type2: "Rock" },
  { number: 112, name: "Rhydon", type1: "Ground", type2: "Rock" },
  { number: 113, name: "Chansey", type1: "Normal" },
  { number: 114, name: "Tangela", type1: "Grass" },
  { number: 115, name: "Kangaskhan", type1: "Normal" },
  { number: 116, name: "Horsea", type1: "Water" },
  { number: 117, name: "Seadra", type1: "Water" },
  { number: 118, name: "Goldeen", type1: "Water" },
  { number: 119, name: "Seaking", type1: "Water" },
  { number: 120, name: "Staryu", type1: "Water" },
  { number: 121, name: "Starmie", type1: "Water", type2: "Psychic" },
  { number: 122, name: "Mr. Mime", type1: "Psychic", type2: "Fairy" },
  { number: 123, name: "Scyther", type1: "Bug", type2: "Flying" },
  { number: 124, name: "Jynx", type1: "Ice", type2: "Psychic" },
  { number: 125, name: "Electabuzz", type1: "Electric" },
  { number: 126, name: "Magmar", type1: "Fire" },
  { number: 127, name: "Pinsir", type1: "Bug" },
  { number: 128, name: "Tauros", type1: "Normal" },
  { number: 129, name: "Magikarp", type1: "Water" },
  { number: 130, name: "Gyarados", type1: "Water", type2: "Flying" },
  { number: 131, name: "Lapras", type1: "Water", type2: "Ice" },
  { number: 132, name: "Ditto", type1: "Normal" },
  { number: 133, name: "Eevee", type1: "Normal" },
  { number: 134, name: "Vaporeon", type1: "Water" },
  { number: 135, name: "Jolteon", type1: "Electric" },
  { number: 136, name: "Flareon", type1: "Fire" },
  { number: 137, name: "Porygon", type1: "Normal" },
  { number: 138, name: "Omanyte", type1: "Rock", type2: "Water" },
  { number: 139, name: "Omastar", type1: "Rock", type2: "Water" },
  { number: 140, name: "Kabuto", type1: "Rock", type2: "Water" },
  { number: 141, name: "Kabutops", type1: "Rock", type2: "Water" },
  { number: 142, name: "Aerodactyl", type1: "Rock", type2: "Flying" },
  { number: 143, name: "Snorlax", type1: "Normal" },
  { number: 144, name: "Articuno", type1: "Ice", type2: "Flying" },
  { number: 145, name: "Zapdos", type1: "Electric", type2: "Flying" },
  { number: 146, name: "Moltres", type1: "Fire", type2: "Flying" },
  { number: 147, name: "Dratini", type1: "Dragon" },
  { number: 148, name: "Dragonair", type1: "Dragon" },
  { number: 149, name: "Dragonite", type1: "Dragon", type2: "Flying" },
  { number: 150, name: "Mewtwo", type1: "Psychic" },
  { number: 151, name: "Mew", type1: "Psychic" },
];

const insert = db.prepare(`
  INSERT INTO pokemon (
    national_dex_number,
    name,
    image,
    type1,
    type2,
    generation
  )
  VALUES (?, ?, ?, ?, ?, ?)
  ON CONFLICT(national_dex_number)
  DO UPDATE SET
    name = excluded.name,
    image = excluded.image,
    type1 = excluded.type1,
    type2 = excluded.type2,
    generation = excluded.generation
`);

for (const p of pokemon) {
  insert.run(
    p.number,
    p.name,
    `pokemon/${p.number}.png`,
    p.type1,
    p.type2 ?? null,
    1
  );
}

const result = db
  .prepare("SELECT COUNT(*) AS total FROM pokemon")
  .get() as { total: number };

console.log(`Seed concluído! ${result.total} Pokémon cadastrados.`);

db.close();
